package software.boos.boosCooldown.command.subcommand;

import software.boos.boosCooldown.command.CommandGroup;
import software.boos.boosCooldown.command.CommandHandler;
import software.boos.boosCooldown.command.HelpCategory;
import software.boos.boosCooldown.command.SubCommand;
import software.boos.boosCooldown.util.BoosChat;
import org.bukkit.command.CommandSender;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Autogenerated {@code /bcd help} — groups subcommands by {@link HelpCategory},
 * filters by the sender's permissions, and walks into groups so nested
 * commands get their own pretty listing (e.g. {@code /bcd help clear}).
 */
public final class HelpSubCommand implements SubCommand {

    private final CommandHandler root;

    public HelpSubCommand(CommandHandler root) {
        this.root = root;
    }

    @Override public String name() { return "help"; }
    @Override public String permission() { return ""; }
    @Override public HelpCategory category() { return HelpCategory.PLAYER; }
    @Override public String description() { return "Show available commands"; }
    @Override public String usage() { return "[section]"; }

    @Override
    public boolean execute(CommandSender sender, String[] args) {
        if (args.length >= 1) {
            SubCommand target = root.find(args[0]);
            if (target instanceof CommandGroup group) {
                printGroup(sender, group);
                return true;
            }
            if (target != null) {
                printSingle(sender, target, "");
                return true;
            }
            BoosChat.sendMessage(sender, "&cUnknown help section: " + args[0]);
            return true;
        }
        printRoot(sender);
        return true;
    }

    private void printRoot(CommandSender sender) {
        BoosChat.sendMessage(sender, "&6=== boosCooldowns — commands ===");
        Map<HelpCategory, java.util.List<SubCommand>> byCategory = new EnumMap<>(HelpCategory.class);
        for (SubCommand cmd : root.visibleCommands()) {
            if (!hasPerm(sender, cmd) || cmd.category() == HelpCategory.INTERNAL) continue;
            byCategory.computeIfAbsent(cmd.category(), k -> new java.util.ArrayList<>()).add(cmd);
        }
        for (HelpCategory cat : HelpCategory.values()) {
            var items = byCategory.get(cat);
            if (items == null || items.isEmpty()) continue;
            BoosChat.sendMessage(sender, "&e" + cat.title() + ":");
            for (SubCommand cmd : items) {
                printSingle(sender, cmd, "  ");
            }
        }
        BoosChat.sendMessage(sender, "&7Type &f/bcd help <section>&7 for details on a group.");
    }

    private void printGroup(CommandSender sender, CommandGroup group) {
        BoosChat.sendMessage(sender, "&6=== /bcd " + group.name() + " ===");
        if (!group.description().isEmpty()) {
            BoosChat.sendMessage(sender, "&7" + group.description());
        }
        List<SubCommand> distinct = group.children().values().stream().distinct().toList();
        for (SubCommand child : distinct) {
            if (!hasPerm(sender, child)) continue;
            printSingle(sender, child, "  ", "/bcd " + group.name() + " ");
        }
    }

    private void printSingle(CommandSender sender, SubCommand cmd, String indent) {
        printSingle(sender, cmd, indent, "/bcd ");
    }

    private void printSingle(CommandSender sender, SubCommand cmd, String indent, String prefix) {
        String usage = cmd.usage().isEmpty() ? "" : " &7" + cmd.usage();
        String description = cmd.description().isEmpty() ? "" : " &8— &f" + cmd.description();
        BoosChat.sendMessage(sender, indent + "&a" + prefix + cmd.name() + "&r" + usage + description);
    }

    private static boolean hasPerm(CommandSender sender, SubCommand cmd) {
        String perm = cmd.permission();
        return perm == null || perm.isEmpty() || sender.hasPermission(perm);
    }

    @Override
    public List<String> tabComplete(CommandSender sender, String[] args) {
        if (args.length != 1) return List.of();
        String prefix = args[0].toLowerCase();
        return root.visibleCommands().stream()
                .filter(c -> hasPerm(sender, c))
                .map(SubCommand::name)
                .filter(n -> n.toLowerCase().startsWith(prefix))
                .collect(Collectors.toList());
    }
}
