package software.boos.boosCooldown.integration;

import software.boos.boosCooldown.BoosCoolDown;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockbukkit.mockbukkit.MockBukkit;
import org.mockbukkit.mockbukkit.ServerMock;
import org.mockbukkit.mockbukkit.entity.PlayerMock;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

import static org.junit.jupiter.api.Assertions.fail;

/**
 * Verifies the 4.0 command layout — nested groups, legacy aliases and the
 * autogenerated {@code /bcd help} output.
 */
class CommandStructureIntegrationTest {

    private ServerMock server;
    private BoosCoolDown plugin;

    @BeforeEach
    void setUp() {
        server = MockBukkit.mock();
        plugin = MockBukkit.load(BoosCoolDown.class);
    }

    @AfterEach
    void tearDown() {
        MockBukkit.unmock();
    }

    private PlayerMock addOp(String name) {
        PlayerMock p = server.addPlayer(name);
        p.setOp(true);
        return p;
    }

    @Test
    void helpListsCategorisedCommands() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns help");
        // MockBukkit's message queue has a small cap, so we only assert the
        // last category survives — full coverage is exercised per-group below.
        assertSaid(admin, m -> m.contains("Diagnostics"));
    }

    @Test
    void helpOnClearGroupExpandsChildren() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns help clear");
        assertSaid(admin, m -> m.contains("/bcd clear cooldowns"));
        assertSaid(admin, m -> m.contains("/bcd clear uses"));
        assertSaid(admin, m -> m.contains("/bcd clear warmups"));
        assertSaid(admin, m -> m.contains("/bcd clear all"));
    }

    @Test
    void helpOnRuleGroupExpandsChildren() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns help rule");
        assertSaid(admin, m -> m.contains("/bcd rule set"));
        assertSaid(admin, m -> m.contains("/bcd rule tempset"));
        assertSaid(admin, m -> m.contains("/bcd rule get"));
    }

    @Test
    void helpOnResetGroupExpandsChildren() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns help reset");
        assertSaid(admin, m -> m.contains("/bcd reset now"));
        assertSaid(admin, m -> m.contains("/bcd reset schedule"));
        assertSaid(admin, m -> m.contains("/bcd reset list"));
    }

    @Test
    void helpOnGrantGroupExpandsChildren() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns help grant");
        assertSaid(admin, m -> m.contains("/bcd grant cooldown"));
        assertSaid(admin, m -> m.contains("/bcd grant uses"));
    }

    @Test
    void legacyClearCooldownsAliasStillRoutes() {
        PlayerMock admin = addOp("Admin");
        PlayerMock target = server.addPlayer("Target");
        target.setOp(false);
        admin.performCommand("booscooldowns clearcooldowns Target");
        assertSaid(admin, m -> m.toLowerCase().contains("cleared"));
    }

    @Test
    void newClearCooldownsFormRoutes() {
        PlayerMock admin = addOp("Admin");
        PlayerMock target = server.addPlayer("Target");
        target.setOp(false);
        admin.performCommand("booscooldowns clear cooldowns Target");
        assertSaid(admin, m -> m.toLowerCase().contains("cleared"));
    }

    @Test
    void legacyScheduleGlobalResetAliasStillRoutes() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns scheduleglobalreset /daily +1h");
        assertSaid(admin, m -> m.toLowerCase().contains("scheduled"));
    }

    @Test
    void newResetScheduleFormRoutes() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns reset schedule /weekly +7d");
        assertSaid(admin, m -> m.toLowerCase().contains("scheduled"));
    }

    @Test
    void legacyInfoAliasRoutesToStatus() {
        PlayerMock admin = addOp("Admin");
        PlayerMock target = server.addPlayer("Target");
        target.setOp(false);
        admin.performCommand("booscooldowns info Target");
        assertSaid(admin, m -> m.toLowerCase().contains("status"));
    }

    @Test
    void emptyCommandShowsHelp() {
        PlayerMock admin = addOp("Admin");
        admin.performCommand("booscooldowns");
        assertSaid(admin, m -> m.contains("boosCooldowns"));
    }

    private static void assertSaid(PlayerMock player, Predicate<String> matcher) {
        List<String> seen = new ArrayList<>();
        String m;
        while ((m = player.nextMessage()) != null) {
            seen.add(m);
            if (matcher.test(m)) return;
        }
        fail("No message matched. Seen: " + seen);
    }
}
